#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt', '~> 2.4.0'

cookbook 'apache2', '~> 2.0.0'

cookbook 'build-essential', '~> 2.0.6'

cookbook 'composer', '~> 1.0.3'

cookbook 'mysql', '~> 5.3.6'

cookbook 'php', '~> 1.4.6'

cookbook 'redisio', '~> 1.7.1'